postgres:
  dbName: chart
  user: postgres
  password: postgres
spotify:
  clientId: <your client ID here>
  clientSecret: <your client secret here>
  userName: <Spotify user who owns the playlist>
  playlists:
    chart: <main playlist>
    yec: <year-end playlist>
    yecSections: <e.g. ["12345", "123fbr", "123fdsge"]>
chartSize: 75
csvDestination: 'src/main/resources/top75'